apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
        azure.workload.identity/use: "true"
      annotations:
        azure.workload.identity/use-identity-binding: "true"
    spec:
      serviceAccountName: default
      containers:
        - name: kubectl-manager
          image: bitnami/kubectl:latest
          command: ["sleep"]
          args: ["infinity"]
          volumeMounts:
            - name: app-config-volume
              mountPath: /app
              readOnly: true
          workingDir: /app
      restartPolicy: Always
      volumes:
        - name: app-config-volume
          configMap:
            name: demo-app-delegation-config
